# Develop override settings

url: http://localhost:4000
# locale                   : "ne-NP"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "prakash014"